services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    networks:
      internal:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.excalidraw.rule=Host(`draw.dharrsan.com`)"
      - "traefik.http.routers.excalidraw.entrypoints=web"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  internal:
    external: true