services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vault.dharrsan.com"
    user: 1000:1000
    volumes:
      - /var/lib/vaultwarden/data:/data/
    networks:
      proxy:
      internal:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.vault.rule=Host(`vault.dharrsan.com`)"
      - "traefik.http.routers.vault.entrypoints=web"
      - "traefik.http.services.vault.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
  internal:
    external: true