services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    volumes:
      - /var/lib/stirlingpdf/data:/configs
    restart: unless-stopped
    networks:
      internal:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stirlingpdf.rule=Host(`pdf.dharrsan.com`)"
      - "traefik.http.routers.stirlingpdf.entrypoints=web"
      - "traefik.http.services.stirlingpdf.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
  internal:
    external: true